server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Esto es vital para aplicaciones Single Page (Vue/React)
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass https://app:8443/api/;
    }
}