server.port=8080
spring.application.name=laboratorio1

spring.datasource.url=jdbc:postgresql://localhost:5432/laboratorio1
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG

app.jwt.secret=esta_es_una_clave_muy_secreta_y_larga_para_cumplir_con_los_256_bits